AkronHoldingTestTask.Web/Models/ErrorViewModel.cs
using System;

namespace AkronHoldingTestTask.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AkronHoldingTestTask.Web/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AkronHoldingTestTask.Core.Domain;
using AkronHoldingTestTask.Core.Dto;
using AkronHoldingTestTask.Services.Car;
using AkronHoldingTestTask.Services.Garage;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AkronHoldingTestTask.Web.Controllers
{
    public class CarController : Controller
    {
        #region Fields

        private readonly ICarService _carService;

        private readonly IGarageService _garageService;

        private readonly IMapper _mapper;

        #endregion

        #region Constructor

        public CarController(IMapper mapper, 
            ICarService carService, 
            IGarageService garageService)
        {
            _mapper = mapper;
            _carService = carService;
            _garageService = garageService;
        }

        #endregion

        #region Methods

        public ActionResult Index()
        {
            return View();
        }

        public async Task<string> GetData()
        {
            var result = await _carService.GetAllAsync();
            var dtos = _mapper.Map<IList<CarDto>>(result);

            return JsonConvert.SerializeObject(dtos);
        }

        [HttpPost]
        public async Task<JsonResult> Save(CarDto record)
        {
            try
            {
                var car = new Car();
                var garage = await _garageService.GetAsync(record.GarageId);

                if (record.Id > 0)
                {
                    car = await _carService.GetAsync(record.Id);
                    if (car == null)
                        return Json(new { result = false });

                    car.Name = record.Name;
                    car.Garage = garage;

                    await _carService.UpdateAsync(car);
                }
                else
                {
                    car.Name = record.Name;
                    car.Garage = garage;

                    await _carService.InsertAsync(car);
                }

                return Json(new { result = true });
            }
            catch (Exception)
            {
                return Json(new { result = false });
            }
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            var car = await _carService.GetAsync(id);
            if (car == null)
                return Json(new { result = false });

            await _carService.DeleteAsync(car);

            return Json(new { result = true });
        }

        #endregion
    }
}

AkronHoldingTestTask.Web/Controllers/CarPropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AkronHoldingTestTask.Core.Domain;
using AkronHoldingTestTask.Core.Dto;
using AkronHoldingTestTask.Services.Car;
using AkronHoldingTestTask.Services.CarProperty;
using AkronHoldingTestTask.Services.Garage;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AkronHoldingTestTask.Web.Controllers
{
    public class CarPropertyController : Controller
    {
        #region Fields

        private readonly ICarService _carService;

        private readonly ICarPropertyService _carPropertyService;

        private readonly IMapper _mapper;

        #endregion

        #region Constructor

        public CarPropertyController(IMapper mapper,
            ICarService carService,
            ICarPropertyService carPropertyService)
        {
            _mapper = mapper;
            _carService = carService;
            _carPropertyService = carPropertyService;
        }

        #endregion

        #region Methods

        public ActionResult Index()
        {
            return View();
        }

        public async Task<string> GetData()
        {
            var result = await _carPropertyService.GetAllAsync();
            var dtos = _mapper.Map<IList<CarPropertyDto>>(result);

            return JsonConvert.SerializeObject(dtos);
        }

        [HttpPost]
        public async Task<JsonResult> Save(CarPropertyDto record)
        {
            try
            {
                var carProperty = new CarProperty();
                var car = await _carService.GetAsync(record.CarId);

                if (record.Id > 0)
                {
                    carProperty = await _carPropertyService.GetAsync(record.Id);
                    if (carProperty == null)
                        return Json(new { result = false });

                    carProperty.Name = record.Name;
                    carProperty.Value = record.Value;
                    carProperty.Car = car;

                    await _carPropertyService.UpdateAsync(carProperty);
                }
                else
                {
                    carProperty.Name = record.Name;
                    carProperty.Value = record.Value;
                    carProperty.Car = car;

                    await _carPropertyService.InsertAsync(carProperty);
                }

                return Json(new { result = true });
            }
            catch (Exception)
            {
                return Json(new { result = false });
            }
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            var carProperty = await _carPropertyService.GetAsync(id);
            if (carProperty == null)
                return Json(new { result = false });

            await _carPropertyService.DeleteAsync(carProperty);

            return Json(new { result = true });
        }

        #endregion
    }
}

AkronHoldingTestTask.Web/Controllers/GarageController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AkronHoldingTestTask.Core.Domain;
using AkronHoldingTestTask.Core.Dto;
using AkronHoldingTestTask.Services.Garage;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AkronHoldingTestTask.Web.Controllers
{
    public class GarageController : Controller
    {
        #region Fields

        private readonly IGarageService _garageService;

        private readonly IMapper _mapper;

        #endregion

        #region Constructor

        public GarageController(IMapper mapper, IGarageService garageService)
        {
            _mapper = mapper;
            _garageService = garageService;
        }

        #endregion

        #region Methods

        public ActionResult Index()
        {
            return View();
        }

        public async Task<string> GetData()
        {

            var result = await _garageService.GetAllAsync();
            var dtos = _mapper.Map<IList<GarageDto>>(result);

            return JsonConvert.SerializeObject(dtos);
        }

        [HttpPost]
        public async Task<JsonResult> Save(Garage record)
        {
            try
            {
                if (record.Id > 0)
                {
                    var garage = await _garageService.GetAsync(record.Id);
                    if (garage == null)
                        return Json(new { result = false });

                    garage.Name = record.Name;

                    await _garageService.UpdateAsync(record);
                }
                else
                {
                    await _garageService.InsertAsync(record);
                }

                return Json(new {result = true});
            }
            catch (Exception)
            {
                return Json(new {result = false});
            }
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            var garage = await _garageService.GetAsync(id);
            if (garage == null)
                return Json(new {result = false});

            await _garageService.DeleteAsync(garage);

            return Json(new {result = true});
        }

        #endregion
    }
}

AkronHoldingTestTask.Web/Views/Car/Index.cshtml
<h2>Car</h2>
<div class="row">
    <div class="col-xs-8">
        <form class="form-inline">
            <div class="form-group">
                <input id="txtName" type="text" placeholder="Name..." class="form-control" />
            </div>
            <button id="btnSearch" type="button" class="btn btn-default">Search</button>
            <button id="btnClear" type="button" class="btn btn-default">Clear</button>
        </form>
    </div>
    <div class="col-xs-4">
        <button id="btnAdd" type="button" class="btn btn-default pull-right">Add New Record</button>
    </div>
</div>
<div class="row" style="margin-top: 10px">
    <div class="col-xs-12">
        <table id="grid"></table>
    </div>
</div>

<div class="modal fade" id="dialogModal" tabindex="-1" role="dialog" aria-labelledby="dialogModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="dialogModalLabel">Garage</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="ID" />
                <div class="form-group">
                    <label for="Name">Name</label>
                    <input type="text" class="form-control" id="Name">
                </div>
                <div class="form-group">
                    <select id="Garages" width="100%" placeholder="Garage..."></select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="btnSave" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

<script>
    var grid, garageDropdown;
    $(document).ready(function () {
        grid = $('#grid').grid({
            primaryKey: 'Id',
            dataSource: '/Car/GetData',
            uiLibrary: 'bootstrap',
            columns: [
                { field: 'Id', width: 32 },
                { field: 'Name', sortable: true },
                { field: 'GarageName', sortable: true },
                { field: 'GarageId', hidden: true },
                { title: '', field: 'Edit', width: 34, type: 'icon', icon: 'glyphicon-pencil', tooltip: 'Edit', events: { 'click': editRecord } },
                { title: '', field: 'Delete', width: 34, type: 'icon', icon: 'glyphicon-remove', tooltip: 'Delete', events: { 'click': deleteRecord } }
            ],
            pager: { limit: 5, sizes: [5, 10, 20] }
        });

        garageDropdown = $('#Garages').dropdown({ dataSource: '/Garage/GetData', valueField: 'Id', textField: 'Name' });

        $('#btnAdd').on('click', function () {
            $('#ID').val('');
            $('#Name').val('');
            garageDropdown.value('');
            $("#dialogModal").modal("toggle");
        });

        $('#btnSave').on('click', saveRecord);

        $('#btnCancel').on('click', function () {
            $("#dialogModal").modal("hide");
        });

        $('#btnSearch').on('click', function () {
            grid.reload({ name: $('#txtName').val() });
        });

        $('#btnClear').on('click', function () {
            $('#txtName').val('');
            grid.reload({ name: '' });
        });

        function editRecord(e) {
            $('#ID').val(e.data.record.Id);
            $('#Name').val(e.data.record.Name);
            garageDropdown.value(e.data.record.GarageId);
            $("#dialogModal").modal("toggle");
        };

        function saveRecord() {
            var record = {
                ID: $('#ID').val(),
                Name: $('#Name').val(),
                GarageId: garageDropdown.value()
            };

            $.ajax({ url: '/Car/Save', data: { record: record }, method: 'POST' })
                .done(function () {
                    $("#dialogModal").modal("hide");
                    grid.reload();
                })
                .fail(function () {
                    alert('Failed to save.');
                    $("#dialogModal").modal("hide");
                });
        };

        function deleteRecord(e) {
            if (confirm('Are you sure?')) {
                $.ajax({ url: '/Car/Delete', data: { id: e.data.id }, method: 'POST' })
                    .done(function () {
                        grid.reload();
                    })
                    .fail(function () {
                        alert('Failed to delete.');
                    });
            }
        };
    });
</script>

AkronHoldingTestTask.Web/Views/CarProperty/Index.cshtml
<h2>CarProperty</h2>
<div class="row">
    <div class="col-xs-8">
        <form class="form-inline">
            <div class="form-group">
                <input id="txtName" type="text" placeholder="Name..." class="form-control" />
            </div>
            <button id="btnSearch" type="button" class="btn btn-default">Search</button>
            <button id="btnClear" type="button" class="btn btn-default">Clear</button>
        </form>
    </div>
    <div class="col-xs-4">
        <button id="btnAdd" type="button" class="btn btn-default pull-right">Add New Record</button>
    </div>
</div>
<div class="row" style="margin-top: 10px">
    <div class="col-xs-12">
        <table id="grid"></table>
    </div>
</div>

<div class="modal fade" id="dialogModal" tabindex="-1" role="dialog" aria-labelledby="dialogModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="dialogModalLabel">Garage</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="ID" />
                <div class="form-group">
                    <label for="Name">Name</label>
                    <input type="text" class="form-control" id="Name">
                </div>
                <div class="form-group">
                    <label for="Value">Value</label>
                    <input type="text" class="form-control" id="Value">
                </div>
                <div class="form-group">
                    <select id="Cars" width="100%" placeholder="Car..."></select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="btnSave" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

<script>
    var grid, carDropdown;
    $(document).ready(function () {
        grid = $('#grid').grid({
            primaryKey: 'Id',
            dataSource: '/CarProperty/GetData',
            uiLibrary: 'bootstrap',
            columns: [
                { field: 'Id', width: 32 },
                { field: 'Name', sortable: true },
                { field: 'Value', sortable: true },
                { field: 'CarName', sortable: true },
                { field: 'CarId', hidden: true },
                { title: '', field: 'Edit', width: 34, type: 'icon', icon: 'glyphicon-pencil', tooltip: 'Edit', events: { 'click': editRecord } },
                { title: '', field: 'Delete', width: 34, type: 'icon', icon: 'glyphicon-remove', tooltip: 'Delete', events: { 'click': deleteRecord } }
            ],
            pager: { limit: 5, sizes: [5, 10, 20] }
        });

        carDropdown = $('#Cars').dropdown({ dataSource: '/Car/GetData', valueField: 'Id', textField: 'Name' });

        $('#btnAdd').on('click', function () {
            $('#ID').val('');
            $('#Name').val('');
            $('#Value').val('');
            carDropdown.value('');
            $("#dialogModal").modal("toggle");
        });

        $('#btnSave').on('click', saveRecord);

        $('#btnCancel').on('click', function () {
            $("#dialogModal").modal("hide");
        });

        $('#btnSearch').on('click', function () {
            grid.reload({ name: $('#txtName').val() });
        });

        $('#btnClear').on('click', function () {
            $('#txtName').val('');
            grid.reload({ name: '' });
        });

        function editRecord(e) {
            $('#ID').val(e.data.record.Id);
            $('#Name').val(e.data.record.Name);
            $('#Value').val(e.data.record.Value);
            carDropdown.value(e.data.record.CarId);
            $("#dialogModal").modal("toggle");
        };

        function saveRecord() {
            var record = {
                ID: $('#ID').val(),
                Name: $('#Name').val(),
                Value: $('#Value').val(),
                CarId: carDropdown.value()
            };

            $.ajax({ url: '/CarProperty/Save', data: { record: record }, method: 'POST' })
                .done(function () {
                    $("#dialogModal").modal("hide");
                    grid.reload();
                })
                .fail(function () {
                    alert('Failed to save.');
                    $("#dialogModal").modal("hide");
                });
        };

        function deleteRecord(e) {
            if (confirm('Are you sure?')) {
                $.ajax({ url: '/CarProperty/Delete', data: { id: e.data.id }, method: 'POST' })
                    .done(function () {
                        grid.reload();
                    })
                    .fail(function () {
                        alert('Failed to delete.');
                    });
            }
        };
    });
</script>

AkronHoldingTestTask.Web/Views/Garage/Index.cshtml
<h2>Garage</h2>
<div class="row">
    <div class="col-xs-8">
        <form class="form-inline">
            <div class="form-group">
                <input id="txtName" type="text" placeholder="Name..." class="form-control" />
            </div>
            <button id="btnSearch" type="button" class="btn btn-default">Search</button>
            <button id="btnClear" type="button" class="btn btn-default">Clear</button>
        </form>
    </div>
    <div class="col-xs-4">
        <button id="btnAdd" type="button" class="btn btn-default pull-right">Add New Record</button>
    </div>
</div>
<div class="row" style="margin-top: 10px">
    <div class="col-xs-12">
        <table id="grid"></table>
    </div>
</div>

<div class="modal fade" id="dialogModal" tabindex="-1" role="dialog" aria-labelledby="dialogModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="dialogModalLabel">Garage</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="ID" />
                <div class="form-group">
                    <label for="Name">Name</label>
                    <input type="text" class="form-control" id="Name">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="btnSave" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

<script>
    var grid;
    $(document).ready(function () {
        grid = $('#grid').grid({
            primaryKey: 'Id',
            dataSource: '/Garage/GetData',
            uiLibrary: 'bootstrap',
            columns: [
                { field: 'Id', width: 32 },
                { field: 'Name', sortable: true },
                { title: '', field: 'Edit', width: 34, type: 'icon', icon: 'glyphicon-pencil', tooltip: 'Edit', events: { 'click': editRecord } },
                { title: '', field: 'Delete', width: 34, type: 'icon', icon: 'glyphicon-remove', tooltip: 'Delete', events: { 'click': deleteRecord } }
            ],
            pager: { limit: 5, sizes: [5, 10, 20] }
        });

        $('#btnAdd').on('click', function () {
            $('#ID').val('');
            $('#Name').val('');
            $("#dialogModal").modal("toggle");
        });

        $('#btnSave').on('click', saveRecord);

        $('#btnCancel').on('click', function () {
            $("#dialogModal").modal("hide");
        });

        $('#btnSearch').on('click', function () {
            grid.reload({ name: $('#txtName').val() });
        });

        $('#btnClear').on('click', function () {
            $('#txtName').val('');
            grid.reload({ name: '' });
        });

        function editRecord(e) {
            $('#ID').val(e.data.record.Id);
            $('#Name').val(e.data.record.Name);
            $("#dialogModal").modal("toggle");
        };

        function saveRecord() {
            var record = {
                ID: $('#ID').val(),
                Name: $('#Name').val()
            };

            $.ajax({ url: '/Garage/Save', data: { record: record }, method: 'POST' })
                .done(function () {
                    $("#dialogModal").modal("hide");
                    grid.reload();
                })
                .fail(function () {
                    alert('Failed to save.');
                    $("#dialogModal").modal("hide");
                });
        };

        function deleteRecord(e) {
            if (confirm('Are you sure?')) {
                $.ajax({ url: '/Garage/Delete', data: { id: e.data.id }, method: 'POST' })
                    .done(function () {
                        grid.reload();
                    })
                    .fail(function () {
                        alert('Failed to delete.');
                    });
            }
        };
    });
</script>

AkronHoldingTestTask.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AkronHoldingTestTask.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AkronHoldingTestTask.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

AkronHoldingTestTask.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AkronHoldingTestTask</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/lib/gijgo/combined/css/gijgo.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/base/jquery-ui.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Garage" asp-action="Index" class="navbar-brand">AkronHoldingTestTask</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Garage" asp-action="Index">Garage</a></li>
                    <li><a asp-area="" asp-controller="Car" asp-action="Index">Car</a></li>
                    <li><a asp-area="" asp-controller="CarProperty" asp-action="Index">CarProperty</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/lib/gijgo/combined/js/gijgo.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js" ></script>

    @RenderSection("Scripts", required: false)

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AkronHoldingTestTask</p>
        </footer>
    </div>
</body>
</html>